config/routes.rb
SaveRupya::Application.routes.draw do
  devise_for :users
  resources :categories
  resources :products
  get 'welcome/index'
  root :to => 'welcome#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
  attr_accessible :status, :description, :name
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  attr_accessible :name, :price, :status, :description, :category_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!, :except => [:index]
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  #create an instance of CategororiesController and run the new method.
  def new
    @category = Category.new
  end
  #If it doesn't save, the user is sent back to the new method.
  #if it save then it takes parameters from the new method and forward to the show method. 
  def create
    @category = Category.new(params[:category])
      if @category.save
        redirect_to @category
      else
        render 'new'
      end 
  end  
  #show method shows data which are saved in create method.
  def show
    @category = Category.find(params[:id])
  end
  #index method shows all the data which are saved in database table.
  def index
    @categories = Category.all
  end
  #edit method used to edit previous stored data.
  def edit
    @category = Category.find(params[:id])
  end
  # its use to update the data if its any error then its redirect to the edit method.
  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(params[:category])
      redirect_to @category
    else
      render 'edit'
    end
  end
  # destroy method delete the record
  def destroy
    @category = Category.find(params[:id])  
    @category.destroy
    redirect_to categories_path
  end 
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  #create an instance of CategororiesController and run the new method.
  def new
    @product = Product.new
  end
  #If it doesn't save, the user is sent back to the new method.
  #if it save then it takes parameters from the new method and forward to the show method. 
  def create
    @product = Product.new(params[:product])
      if @product.save
        redirect_to @product
      else
        render 'new'
      end 
  end  
  #show method shows data which are saved in create method.
  def show
    @product = Product.find(params[:id])
  end
  #index method shows all the data which are saved in database table.
  def index
    @products = Product.all
  end
  #edit method used to edit previous stored data.
  def edit
    @product = Product.find(params[:id])
  end
  # its use to update the data if its any error then its redirect to the edit method.
  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(params[:product])
      redirect_to @product
    else
      render 'edit'
    end
  end
  # destroy method delete the record
  def destroy
    @product = Product.find(params[:id])  
    @product.destroy
    redirect_to products_path
  end 
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_filter :authenticate_user!
  layout "welcome"
  # index method initialize and show the index.
  def index
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %> 
  <% if @category.present? && @category.errors.any? %>
    <div id="error_explanation">
      <h5 style="color:DarkRed">
        <%= pluralize(@category.errors.count, "error") %> 
        prohibited
        this category from being saved:</h5>
      <ul>
        <% @category.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <center><h3>New Category</h3></center>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.radio_button :status, true %> 
    <%= f.label :status_true, 'Active' %>
    <%= f.radio_button :status, false %>
    <%= f.label :status_false, 'Inactive' %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/categories/index.html.erb
<div class = "title">Category List</div>
<table border="1px">
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Number of producte</th>
    <th colspan = 3>Action</th>
  </tr>
  <% @categories.each do |c| %>
    <tr>
      <td><%= link_to c.name, c %></td>
      <td><%= c.description  %></td>
      <td><%= c.products.count %></td>
      <td><%= link_to 'Show',category_path(c)%></td>
      <td><%= link_to 'Edit',edit_category_path(c)%></td>
      <td><%= button_to 'Delete', {controller: :categories ,action: :destroy , id: c.id}, confirm: "Are you sure?" ,method: :delete%>
      </td>
    </tr>
  <% end %>
</table>
<%= link_to 'New Category',new_category_path()%>

app/views/categories/new.html.erb
<%= render "form" %>
<%= link_to "Show All Category", categories_path %>

app/views/categories/show.html.erb
<div class="title">Category List</div>
<table border="1px">
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Number of producte</th>
    <th colspan=3>Action</th>
  </tr>
  <% Category.all.each do |c| %>
    <tr>
      <td><%= link_to c.name, c %></td>
      <td><%= c.description  %></td>
      <td><%= c.products.count %></td>
      <td><%= link_to 'Show',category_path(c)%></td>
      <td><%= link_to 'Edit',edit_category_path(c)%></td>
      <td><%= button_to 'Delete', {controller: :categories ,action: :destroy , id: c.id}, confirm: "Are you sure?" ,method: :delete%>
      </td>
    </tr>
  <% end %>
</table>
<div class="title">Selected Category Product List</div>
<p>
  <strong>name:</strong>
  <%= @category.name %>
</p>
<table border="1px">
  <tr>
    <th>Name</th>
    <th>price</th>
    <th>Description</th>
  </tr>
  <% @category.products.each do |c| %>
  <tr>
    <td><%= c.name %></td>
    <td><%= c.price %></td>
    <td><%= c.description  %></td>
  </tr>  
  <% end %>
</table>  
<%= link_to 'Show All categories', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SaveRupya</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag :application %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
  
  <%= render "shared/header" %>
  <div class="p1">
    <div class="p2">
      <%= yield %>
    </div>  
  </div>
  <%= render "shared/footer" %>
</body>
</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SaveRupya</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag :application %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
  
  <%= render "shared_welcome/welcome_header" %>
  <div class="p1">
    <div class="p2">
      <%= yield %>
    </div>  
  </div>  
  <%= render "shared_welcome/welcome_footer" %>
</body>
</html>
  

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %> 
  <% if @product.present? && @product.errors.any? %>
    <div id="error_explanation">
      <h5 style="color:DarkRed">
        <%= pluralize(@product.errors.count, "error") %> 
        prohibited
        this product from being saved:</h5>
      <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <center><h3>New product</h3></center>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.radio_button :status, true %> 
    <%= f.label :status_true, 'Active' %>
    <%= f.radio_button :status, false%>
    <%= f.label :status_false, 'Inactive' %>
  </p>

  <p>
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </p>

  <p>
    <%= f.label :category_id %><br>
    <%= f.collection_select(:category_id, Category.all, :id, :name)%>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/products/edit.html.erb
<%= render "form" %>

app/views/products/index.html.erb
<div class = "title">Product List</div>
<table border="1px">
  <tr>
    <th>Name</th>
    <th>Status</th>
    <th>Price</th>
    <th>Description</th>
    <th colspan=3>Action</th>
  </tr>
  
  <% @products.each do |p| %>
    <tr>
      <td><%= p.name %></td>
      <td><%= p.status %></td>
      <td><%= p.price %></td>
      <td><%= p.description  %></td>
      <td><%= link_to 'Show',product_path(p)%></td>
      <td><%= link_to 'Edit',edit_product_path(p)%></td>
      <td><%= button_to 'Delete', {controller: :products ,action: :destroy , id: p.id}, confirm: "Are you sure?" ,method: :delete%></td>
    </tr>
  <% end %>
</table>

<%= link_to 'New Product',new_product_path()%>

app/views/products/new.html.erb
<%= render "form" %>
<%= link_to "Show All product", products_path %>

app/views/products/show.html.erb
<p>
  <strong>name:</strong>
  <%= @product.name %>
</p>

<p>
  <%# if @product.status.true? %>
  <strong>status:</strong>
  <%= @product.status %>
</p>

<p>
  <strong>price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>description:</strong>
  <%= @product.description %>
</p>
<%= link_to 'Show All categories', products_path %>

app/views/shared/_header.html.erb
<div class="header">

  <% if user_signed_in? %>
  <div class="p">
    Log-In :<strong><%= current_user.email %></strong><br>
    <%= link_to 'Account setting', edit_user_registration_path %>
    |
    <%= link_to "Logout", destroy_user_session_path, method: :delete %>
  </div>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path %> |
    <%= link_to "Login", new_user_session_path %>
  <% end %>
  <div class="navigation">
      <% if current_user.present?  && current_user.id.present?%>
        <%=link_to "Home", welcome_index_path %>
        <%=link_to "Category", categories_path %>
        <%=link_to "Product", products_path %>
      <% end %>    
  </div>
</div> 

app/views/shared_welcome/_footer.html.erb
<div class="footer">
  <a href="http://www.clariontechnologies.com" target="_blank">clariontechnologies.co.in</a>
</div> 

app/views/shared_welcome/_welcome_footer.html.erb
<div class="footer">
  <a href="http://www.clariontechnologies.com" target="_blank">clariontechnologies.co.in</a>
</div> 

app/views/shared_welcome/_welcome_header.html.erb
<div class="header">
  <% if user_signed_in? %>
  <div class="p">
    Log-In :<strong><%= current_user.email %></strong><br>
    <%= link_to 'Account setting', edit_user_registration_path %>
    |
    <%= link_to "Logout", destroy_user_session_path, method: :delete %>
  </div>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path %> |
    <%= link_to "Login", new_user_session_path %>
  <% end %>

  <div class="navigation1">
        <%=link_to "Home", welcome_index_path %>
        <%=link_to "Category", categories_path %>
        <%=link_to "Product", products_path %> 
  </div>
</div> 

app/views/welcome/index.html.erb
<center><h2>Save Rupya</h2></center>
  <%= image_tag "index.jpeg",class: "img", :alt => "rss feed" %>
  <table>
    <% Category.all.each do |c| %>
      <tr>
        <td><%= c.name %></td>
        <td><%= c.description %></td>
      </tr>
    <% end %>
  </table>